### ISSUE TITLE
Can you add opacity and font size settings? And position change settings :)

### ISSUE THREAD

**Issue by MegaVolt-TM** [Th3Fanbus/Th3UObjectCounter#1]
Can you add opacity and font size settings? And position change settings :)

**Comment by Th3Fanbus** [comment]
Uh, I just saw this. If the problem is that the counter gets in the way, I added a config option to hide it when the count is below the thresholds. Most people don't need to see the counter all the time, only when it's time to restart.

If you really need it, I could look into implementing opacity and font size settings (I think there's like three separate font sizes for each text element).

I'm not sure how to make the counter position configurable in a way that doesn't cause other problems. If I recall correctly, the counter widget is currently injected to some element of the base game HUD (I think it was the autosave notification thing).

**Comment by Th3Fanbus** [comment]
Sorry, I've decided against it. This mod is primarily meant to avoid crashes: with default settings, the counter shows up when it's time to restart (yellow means "when you have the time, consider restarting the game", red means "save and restart the game ASAP"). It could also be used as a developer tool, but I haven't found a use-case where it would be useful.

I don't understand why one would want to have the counter always visible. It just shows two numbers, which are pretty much meaningless on their own (what actually matters is whether the UObject count is getting close to the limit, as exceeding the limit results in a crash).
